config/routes.rb
Rails.application.routes.draw do
  

  get 'welcome_calculator/show'

 scope controller: 'subtract' do
    get 'subtract/form', action: 'form', as: 'subtract_form'
    post '/subtract/result' => 'subtract#result', as: 'subtract_result'
  end
  
  scope controller: 'add' do
    get 'add/form', action: 'form', as: 'add_form'
    post 'add/result'
  end
  
  scope controller: 'multiply' do
    get 'multiply/form', action: 'form', as: 'multiply_form'
    post 'multiply/result'
  end

  scope controller: 'divide' do
    get 'divide/form', action: 'form', as: 'divide_form'
    post 'divide/result'
  end

  root 'welcome_calculator#show'

end

app/controllers/add_controller.rb
class AddController < ApplicationController
  	def form
  	end

  	def result
 	 	@first = params[:first].to_i
		@second = params[:second].to_i
	  	@result = @first + @second
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/divide_controller.rb
class DivideController < ApplicationController
  def form
  end

  def result
  	@first = params[:first].to_f
  	@second = params[:second].to_f
  	@result = @first / @second
  	@first = params[:first].to_i
  	@second = params[:second].to_i
  end


end

app/controllers/multiply_controller.rb
class MultiplyController < ApplicationController
  def form
  end

  def result
  		@first = params[:first].to_i
		@second = params[:second].to_i
	  	@result = @first * @second
  end
end

app/controllers/subtract_controller.rb
class SubtractController < ApplicationController
  def form
  end

  	def result
 	 	@first = params[:first].to_i
		@second = params[:second].to_i
	  	@result = @first - @second
	end
end

app/controllers/welcome_calculator_controller.rb
class WelcomeCalculatorController < ApplicationController
  def show
  end
end

app/helpers/add_helper.rb
module AddHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divide_helper.rb
module DivideHelper
end

app/helpers/multiply_helper.rb
module MultiplyHelper
end

app/helpers/subtract_helper.rb
module SubtractHelper
end

app/helpers/welcome_calculator_helper.rb
module WelcomeCalculatorHelper
end

app/views/add/form.html.erb
<%= form_tag add_result_path do %>
  <%= number_field_tag :first %>
  +
  <%= number_field_tag :second %>
  <%= submit_tag "add" %>
<% end %>
<%= link_to 'Back to main page', welcome_calculator_show_path %>

app/views/add/result.html.erb
<%= @first %> + <%= @second %> = <%= @result %>
<br/>
<%= link_to 'back', add_form_path %>

app/views/divide/form.html.erb
<%= form_tag divide_result_path do %>
  <%= number_field_tag :first %>
 /
  <%= number_field_tag :second %>
  <%= submit_tag "divide" %>
<% end %>
<%= link_to 'Back to main page', welcome_calculator_show_path %>

app/views/divide/result.html.erb
<%= @first %> / <%= @second %> = <%= @result %>
<br/>
<%= link_to 'back', divide_form_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MathApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/multiply/form.html.erb
<%= form_tag multiply_result_path do %>
  <%= number_field_tag :first %>
 x
  <%= number_field_tag :second %>
  <%= submit_tag "multiply" %>
<% end %>
<%= link_to 'Back to main page', welcome_calculator_show_path %>

app/views/multiply/result.html.erb
<%= @first %> x <%= @second %> = <%= @result %>
<br/>
<%= link_to 'back', multiply_form_path %>

app/views/subtract/form.html.erb
<%= form_tag subtract_result_path do %>
  <%= number_field_tag :first %>
 -
  <%= number_field_tag :second %>
  <%= submit_tag "subtract" %>
<% end %>
<%= link_to 'Back to main page', welcome_calculator_show_path %>

app/views/subtract/result.html.erb
<%= @first %> - <%= @second %> = <%= @result %>
<br/>
<%= link_to 'back', subtract_form_path %>

app/views/welcome_calculator/show.html.erb
<h1>Calculator</h1>
<p>What would you like to do?</p>
<%= link_to 'Add', add_form_path %>
<%= link_to 'Subtract', subtract_form_path %>
<%= link_to 'Multiply', multiply_form_path %>
<%= link_to 'Divide', divide_form_path %>